# Generated by Django 4.2.6 on 2023-11-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_alter_projet_nomprojet'),
    ]

    operations = [
        migrations.CreateModel(
            name='RDUE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entite', models.CharField(choices=[('AGRIAL', 'AGRIAL'), ('COOPAA-HS', 'COOPAA-HS')], max_length=255)),
                ('produits', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('chaine_appro', models.TextField()),
                ('pays_origine', models.CharField(max_length=150)),
                ('fournisseur', models.CharField(max_length=150)),
                ('zone_arisque', models.CharField(choices=[('OUI', 'OUI'), ('NON', 'NON')], default='NON', max_length=10)),
                ('liste_zone', models.CharField(max_length=250)),
                ('exp_illegale', models.CharField(choices=[('OUI', 'OUI'), ('NON', 'NON')], default='NON', max_length=10)),
                ('mesure_preventives', models.TextField()),
                ('suivi_mesure', models.TextField()),
                ('efficacite_mesure', models.TextField()),
                ('communication', models.TextField()),
                ('action_comm', models.TextField()),
                ('action_non_conformite', models.TextField()),
            ],
        ),
    ]
