# Generated by Django 4.2.6 on 2023-11-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_remove_rdue_date_rdue_add_le_rdue_update_le'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdue',
            name='action_comm',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rdue',
            name='action_non_conformite',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rdue',
            name='chaine_appro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rdue',
            name='communication',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rdue',
            name='efficacite_mesure',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rdue',
            name='fournisseur',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='rdue',
            name='liste_zone',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='rdue',
            name='mesure_preventives',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rdue',
            name='pays_origine',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='rdue',
            name='produits',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rdue',
            name='suivi_mesure',
            field=models.TextField(blank=True, null=True),
        ),
    ]
