# Generated by Django 4.2.6 on 2023-12-04 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_risquerdue_remove_rdue_fournisseur_rdue_evaluateur_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rdue',
            options={'verbose_name_plural': '28. QUESTIONNAIRES RDUE'},
        ),
        migrations.AlterModelOptions(
            name='risquerdue',
            options={'ordering': ['libelle'], 'verbose_name_plural': '28. RISQUES RDUE'},
        ),
    ]
