# Generated by Django 4.2.6 on 2023-12-11 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0009_alter_rdue_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='risquerdue',
            name='cooperative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.cooperative'),
        ),
    ]
