# Generated by Django 4.2.6 on 2024-03-29 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0019_angrais_produit_phyto_theme_enquete_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='angrais',
            options={'ordering': ['libelle'], 'verbose_name_plural': '33. ENGRAIS'},
        ),
    ]
