# Generated by Django 4.2.6 on 2024-04-11 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0021_rename_angrais_engrais'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acte_Propriete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'ACTE DE PROPIETE',
                'ordering': ['libelle'],
            },
        ),
        migrations.AddField(
            model_name='parcelle',
            name='doc_acte_propriete',
            field=models.FileField(blank=True, null=True, upload_to='Documents/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='is_doc_propriete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rdue',
            name='produits',
            field=models.CharField(choices=[('CACAO', 'CACAO'), ('CAFE', 'CAFE'), ('HEVEAS', 'HEVEAS'), ('SOJA', 'SOJA'), ('PALMIER', 'PALMIER A HUILE'), ('BOIS', 'BOIS'), ('BOEUF', 'BOEUF')], default='CACAO', max_length=255, verbose_name='PRODUITS COMMERCIALISES'),
        ),
        migrations.AlterField(
            model_name='rdue',
            name='zone_arisque',
            field=models.CharField(choices=[('EXPLOITATION ILLEGALE DU BOIS', 'EXPLOITATION ILLEGALE DU BOIS'), ('ORPAILLAGE', 'ORPAILLAGE'), ('DEFORESTATION', 'DEFORESTATION'), ('TRAVAIL DES ENFANTS', 'TRAVAIL DES ENFANTS'), ('AUCUN', 'AUCUN')], default='AUCUN', max_length=255, verbose_name='Activités portant à controverse'),
        ),
        migrations.CreateModel(
            name='Enquete_Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_epouse', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name="NBRE D'EPOUSE ")),
                ('nb_enfant', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name="NBRE TOTAL D'ENFANTS")),
                ('nb_personne', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='PERSONNES A CHARGE')),
                ('is_compte_bancaire', models.BooleanField(default=False)),
                ('is_mobile_money', models.BooleanField(default=False)),
                ('numero_mobile_money', models.CharField(blank=True, max_length=10, null=True)),
                ('revenu_moyen', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('producteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquetes_producteur', to='myapi.producteur')),
                ('thematique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquetes_thematiques', to='myapi.theme_enquete', verbose_name='THEMATIQUE')),
            ],
            options={
                'verbose_name_plural': '34. ENQUETES SOCIALES',
                'ordering': ['thematique'],
            },
        ),
        migrations.CreateModel(
            name='Age_scolarise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_enfant_scolarise', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='NOMBRE ENFANT SCOLARISE')),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='age_enfant_scolarise', to='myapi.age', verbose_name='AGE')),
                ('enquete_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='age_enfant_scolarise', to='myapi.enquete_social')),
            ],
            options={
                'verbose_name_plural': '36. AGE ENFANTS SCOLARISES',
            },
        ),
        migrations.CreateModel(
            name='Age_enfant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_enfant', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='NOMBRE ENFANT')),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='age_enfant', to='myapi.age', verbose_name='AGE')),
                ('enquete_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='age_enfant_enquetes', to='myapi.enquete_social')),
            ],
            options={
                'verbose_name_plural': '35. AGE ENFANT',
            },
        ),
        migrations.AddField(
            model_name='parcelle',
            name='type_acte_propriete',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.acte_propriete'),
        ),
    ]
