# Generated by Django 4.2.6 on 2024-04-11 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0023_alter_age_enfant_options_enquete_exploitation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detail_engrais',
            options={'verbose_name_plural': '40. DETAILS ENGRAIS'},
        ),
    ]
