# Generated by Django 4.2.6 on 2024-06-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0029_alter_cooperative_projet'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelle',
            name='is_map',
            field=models.BooleanField(default=False),
        ),
    ]
