# Generated by Django 4.2.6 on 2024-07-02 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0031_rename_is_map_parcelle_is_mapped_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cooperative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.cooperative')),
            ],
            options={
                'verbose_name_plural': '41. Sections Points',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=250, null=True)),
                ('contacts', models.CharField(blank=True, max_length=50, null=True)),
                ('photo', models.ImageField(null=True, upload_to='photo_point/')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.section')),
            ],
            options={
                'verbose_name_plural': '42. Points',
                'ordering': ['libelle'],
            },
        ),
    ]
