# Generated by Django 4.2.6 on 2024-07-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0033_point_latitude_point_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo_point/'),
        ),
    ]
