# Generated by Django 4.2.6 on 2024-07-02 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0034_alter_point_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.sectionpoint'),
        ),
    ]
