# Generated by Django 4.2.6 on 2024-07-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0035_alter_point_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='point_type',
            field=models.CharField(blank=True, choices=[('ECOLE', 'ECOLE'), ('HOPITAL', 'HOPITAL')], max_length=20, null=True),
        ),
    ]
