# Generated by Django 4.2.6 on 2024-10-16 11:24

from django.db import migrations, models
import django.db.models.deletion
import myapi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acte_Propriete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '41. ACTE DE PROPRIETE',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': '30. TRANCHES AGES',
            },
        ),
        migrations.CreateModel(
            name='Campagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=200, null=True)),
                ('dateDebut', models.DateField(blank=True, null=True)),
                ('DateFin', models.DateField(blank=True, null=True)),
                ('etat', models.BooleanField(default=True)),
                ('duree_campagne', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '05. Campagnes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CategorieEspece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': '06. Categories especes',
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '27. CERTIFICATION PARCELLE',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Cooperative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respCoop', models.CharField(blank=True, max_length=255, null=True)),
                ('numConnaissement', models.CharField(blank=True, max_length=255, null=True)),
                ('numRegistre', models.CharField(blank=True, max_length=255, null=True)),
                ('nomCoop', models.CharField(blank=True, max_length=500, null=True)),
                ('contacts', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo_coop/')),
                ('etat', models.BooleanField(default=True)),
                ('siege', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '12. Cooperatives',
            },
        ),
        migrations.CreateModel(
            name='Countrie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': '01. Pays',
            },
        ),
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=250, null=True)),
                ('prix_unitaire_culture', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cooperative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.cooperative')),
            ],
            options={
                'verbose_name_plural': '16. Cultures',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Engrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': '33. ENGRAIS',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Espece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accronyme', models.CharField(max_length=250, verbose_name='NOM SCIENTIFIQUE')),
                ('libelle', models.CharField(max_length=250, unique=True, verbose_name='NOM USUEL')),
                ('densite', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='DENSITE SPECIFIQUE')),
                ('hmax', models.FloatField(default=0)),
                ('dmax', models.FloatField(default=0)),
                ('co2_annuel', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='CO2/AN')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.categorieespece')),
            ],
            options={
                'verbose_name_plural': '07. Especes',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('libelle', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'fournisseur',
                'verbose_name_plural': '43. FOURNISSEURS',
            },
        ),
        migrations.CreateModel(
            name='GroupeProducteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '14. Groupe de producteurs',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='ModeAcquisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': "17. Mode d'acquisition",
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Monitoring',
            fields=[
                ('code', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('taux_reussite', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campagne', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.campagne')),
            ],
            options={
                'verbose_name_plural': '21. Monitoring',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ObservationMortalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': '23. Cause de mortalite',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('code', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('latitude', models.CharField(blank=True, max_length=200, null=True)),
                ('longitude', models.CharField(blank=True, max_length=200, null=True)),
                ('is_mapped', models.BooleanField(default=False)),
                ('superficie', models.FloatField(default=0)),
                ('annee_acquis', models.CharField(blank=True, max_length=150, null=True)),
                ('age_parcelle', models.PositiveIntegerField(default=0)),
                ('image_du_titre_de_propriete', models.ImageField(blank=True, null=True, upload_to='titre_de_propriete/')),
                ('fichier_de_mappage', models.ImageField(blank=True, null=True, upload_to='fichier_mapping/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acquisition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.modeacquisition')),
                ('campagne', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.campagne')),
                ('culture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.culture')),
            ],
            options={
                'verbose_name_plural': '18. Parcelles',
            },
        ),
        migrations.CreateModel(
            name='Produit_Phyto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': '32. PRODUITS PHYTO',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomProjet', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('dateDebut', models.DateField(blank=True, null=True)),
                ('dateFin', models.DateField(blank=True, null=True)),
                ('objectif', models.CharField(blank=True, max_length=100, null=True)),
                ('etat', models.BooleanField(default=True)),
                ('plant_aproduit', models.FloatField(default=0)),
                ('carbon_astock', models.FloatField(default=0)),
                ('emp_engageof_proj', models.IntegerField(default=0)),
                ('logo', models.ImageField(blank=True, upload_to=myapi.models.upload_logo_site, verbose_name='Logo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('countrie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.countrie')),
            ],
            options={
                'verbose_name_plural': '03. Projets',
            },
        ),
        migrations.CreateModel(
            name='SimulateCarbon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anneePeuplement', models.IntegerField(default=1)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('totalCarbone', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '08. Simulation carbone',
            },
        ),
        migrations.CreateModel(
            name='Theme_Enquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': '31. THEMATIQUES ENQUETES',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('nom', models.CharField(max_length=100, null=True)),
                ('prenom', models.CharField(max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('tel', models.CharField(max_length=100, null=True)),
                ('fonction', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=300)),
                ('is_online', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superadmin', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_client', models.BooleanField(default=False)),
                ('is_responsable', models.BooleanField(default=False)),
                ('is_supervisor', models.BooleanField(default=False)),
                ('is_gestionnaire', models.BooleanField(default=False)),
                ('is_adg', models.BooleanField(default=False)),
                ('is_technicien', models.BooleanField(default=False)),
                ('is_pepinieriste', models.BooleanField(default=False)),
                ('permission_ptr', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='utilisateur', to='auth.permission')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for the user utilisateur.', null=True, related_name='utilisateurs', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': '02. Utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='UserProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etatuser', models.BooleanField(default=True)),
                ('projet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.projet')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.utilisateur')),
            ],
            options={
                'verbose_name_plural': '04. Users on projects',
            },
        ),
        migrations.CreateModel(
            name='SectionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cooperative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.cooperative')),
            ],
            options={
                'verbose_name_plural': '41. Sections Points',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cooperative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.cooperative')),
            ],
            options={
                'verbose_name_plural': '13. Sections',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='SaisonRecolte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=250, null=True)),
                ('cooperative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.cooperative')),
            ],
            options={
                'verbose_name_plural': '25. Saisons de recolte',
            },
        ),
        migrations.CreateModel(
            name='RisqueRDUE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('cooperative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.cooperative')),
            ],
            options={
                'verbose_name_plural': '28. RISQUES RDUE',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=250, null=True)),
                ('chef_lieu_reg', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('countrie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.countrie')),
            ],
            options={
                'verbose_name_plural': '11. Regions',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='RecolteProducteur',
            fields=[
                ('code', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('estimation_production', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=1000, null=True)),
                ('nbre_sacs', models.IntegerField(default=0)),
                ('poids_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=1000, null=True)),
                ('prix_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campagne', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.campagne')),
                ('culture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.culture')),
                ('parcelle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.parcelle')),
                ('saison', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.saisonrecolte')),
            ],
            options={
                'verbose_name_plural': '26. Recoltes producteurs',
            },
        ),
        migrations.CreateModel(
            name='RDUE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluateur', models.CharField(blank=True, max_length=255, null=True, verbose_name='ENQUETEUR')),
                ('produits', models.CharField(choices=[('CACAO', 'CACAO'), ('CAFE', 'CAFE'), ('HEVEAS', 'HEVEAS'), ('SOJA', 'SOJA'), ('PALMIER', 'PALMIER A HUILE'), ('BOIS', 'BOIS'), ('BOEUF', 'BOEUF')], default='CACAO', max_length=255, verbose_name='PRODUITS COMMERCIALISES')),
                ('chaine_appro', models.CharField(blank=True, choices=[('MEMBRES', 'MEMBRES'), ('AUTRE', 'AUTRE')], default='MEMBRES', max_length=255, null=True, verbose_name='APPROVISIONNEMENT')),
                ('zone_arisque', models.CharField(choices=[('EXPLOITATION ILLEGALE DU BOIS', 'EXPLOITATION ILLEGALE DU BOIS'), ('ORPAILLAGE', 'ORPAILLAGE'), ('DEFORESTATION', 'DEFORESTATION'), ('TRAVAIL DES ENFANTS', 'TRAVAIL DES ENFANTS'), ('AUCUN', 'AUCUN')], default='AUCUN', max_length=255, verbose_name='Activités portant à controverse')),
                ('mesure_preventives', models.TextField(blank=True, null=True, verbose_name='Mesures Correctives')),
                ('suivi_mesure', models.TextField(blank=True, null=True)),
                ('efficacite_mesure', models.TextField(blank=True, null=True)),
                ('add_le', models.DateTimeField(auto_now_add=True)),
                ('update_le', models.DateTimeField(auto_now=True)),
                ('entite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.cooperative', verbose_name='ORGANISATION')),
                ('pays_origine', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapi.countrie', verbose_name="PAYS D'ORIGINE")),
            ],
            options={
                'verbose_name_plural': '29. QUESTIONNAIRES RDUE',
            },
        ),
        migrations.AddField(
            model_name='projet',
            name='respo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.utilisateur'),
        ),
        migrations.CreateModel(
            name='Producteur',
            fields=[
                ('code', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('nomComplet', models.CharField(blank=True, max_length=250, null=True)),
                ('contacts', models.CharField(blank=True, max_length=50, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo_prod/')),
                ('nbParc', models.IntegerField(default=0)),
                ('etat', models.BooleanField(default=True)),
                ('lieu_habitation', models.CharField(blank=True, max_length=150, null=True)),
                ('representant', models.CharField(blank=True, max_length=250, null=True)),
                ('nbreMembre', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campagne', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.campagne')),
                ('groupe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.groupeproducteur')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.section')),
            ],
            options={
                'verbose_name_plural': '15. Producteurs',
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_type', models.CharField(blank=True, choices=[('ECOLE', 'ECOLE'), ('HOPITAL', 'HOPITAL')], max_length=20, null=True)),
                ('libelle', models.CharField(blank=True, max_length=250, null=True)),
                ('contacts', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.CharField(blank=True, max_length=200, null=True)),
                ('longitude', models.CharField(blank=True, max_length=200, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo_point/')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.sectionpoint')),
            ],
            options={
                'verbose_name_plural': '42. Points',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Planting',
            fields=[
                ('code', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('plant_existant', models.IntegerField(default=0)),
                ('plant_recus', models.IntegerField(default=0)),
                ('note_plant_existant', models.TextField(null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campagne', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.campagne')),
                ('parcelle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.parcelle')),
            ],
            options={
                'verbose_name_plural': '19. Plantings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='parcelle',
            name='producteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.producteur'),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='risque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.risquerdue'),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='titre_de_propriete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.acte_propriete'),
        ),
        migrations.CreateModel(
            name='ObservationMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitoring', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.monitoring')),
                ('observation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.observationmortalite')),
            ],
            options={
                'verbose_name_plural': '24. Observations monitoring',
            },
        ),
        migrations.CreateModel(
            name='MonitoringDetail',
            fields=[
                ('code', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('plant_denombre', models.IntegerField(default=0)),
                ('taux_reussite', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('espece', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.espece')),
                ('monitoring', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.monitoring')),
            ],
            options={
                'verbose_name_plural': '22. Monitoring par espèces',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='monitoring',
            name='planting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.planting'),
        ),
        migrations.CreateModel(
            name='EspeceSimulate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('carboneStocke', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('espece', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.espece')),
                ('simulate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.simulatecarbon')),
            ],
            options={
                'verbose_name_plural': '09. Especes de simulation',
            },
        ),
        migrations.CreateModel(
            name='Enquete_Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_epouse', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name="NBRE D'EPOUSE ")),
                ('nb_enfant', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name="NBRE TOTAL D'ENFANTS")),
                ('nb_personne', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='PERSONNES A CHARGE')),
                ('is_compte_bancaire', models.BooleanField(default=False)),
                ('is_mobile_money', models.BooleanField(default=False)),
                ('numero_mobile_money', models.CharField(blank=True, max_length=10, null=True)),
                ('revenu_moyen', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('producteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquetes_producteur', to='myapi.producteur')),
                ('thematique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquetes_thematiques', to='myapi.theme_enquete', verbose_name='THEMATIQUE')),
            ],
            options={
                'verbose_name_plural': '34. ENQUETES SOCIALES',
                'ordering': ['thematique'],
            },
        ),
        migrations.CreateModel(
            name='Enquete_Exploitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main_doeuvre_homme', models.BooleanField(default=False)),
                ('nb_main_doeuvre_homme', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('salaire_moyen_homme', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('is_main_doeuvre_femme', models.BooleanField(default=False)),
                ('nb_main_doeuvre_femme', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('salaire_moyen_femme', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('is_produit_phyto', models.BooleanField(default=False)),
                ('is_engrais', models.BooleanField(default=False)),
                ('Parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquete_parcelle', to='myapi.parcelle')),
                ('culture_principale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquete_culture_principale', to='myapi.culture')),
                ('culture_secondaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enquete_culture_secondaire', to='myapi.culture')),
                ('thematique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.theme_enquete', verbose_name='THEMATIQUE')),
            ],
            options={
                'verbose_name_plural': '37. ENQUETES EXPLOITATION',
            },
        ),
        migrations.CreateModel(
            name='DetailPlanting',
            fields=[
                ('code', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('plants', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('espece', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.espece')),
                ('planting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.planting')),
            ],
            options={
                'verbose_name_plural': '20. Especes Plantées',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Detail_phyto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(blank=True, max_length=255, null=True)),
                ('enquete_exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.enquete_exploitation')),
                ('produits_phyto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.produit_phyto')),
            ],
            options={
                'verbose_name_plural': '39. DETAILS PRODUITS PHYTO',
            },
        ),
        migrations.CreateModel(
            name='Detail_Engrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_engrais', models.CharField(blank=True, max_length=255, null=True)),
                ('engrais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.engrais')),
                ('enquete_exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.enquete_exploitation')),
            ],
            options={
                'verbose_name_plural': '40. DETAILS ENGRAIS',
            },
        ),
        migrations.CreateModel(
            name='Detail_Age_Homme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_homme', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('age_homme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.age')),
                ('enquete_exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.enquete_exploitation')),
            ],
            options={
                'verbose_name_plural': "38. DETAILS AGE MAIN D'OEUVRE HOMMES",
            },
        ),
        migrations.CreateModel(
            name='Detail_Age_Femme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_femme', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('age_femme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.age')),
                ('enquete_exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.enquete_exploitation')),
            ],
            options={
                'verbose_name_plural': "39. DETAILS AGE MAIN D'OEUVRE FEMME",
            },
        ),
        migrations.AddField(
            model_name='cooperative',
            name='fournisseur',
            field=models.ManyToManyField(blank=True, related_name='fournisseurs_cooperative', to='myapi.fournisseur'),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.projet'),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.region'),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='respo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.utilisateur'),
        ),
        migrations.CreateModel(
            name='CampagneProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campagne', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.campagne')),
                ('projet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.projet')),
            ],
            options={
                'verbose_name_plural': '10. Campagnes par projets',
            },
        ),
        migrations.AddField(
            model_name='campagne',
            name='respo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.utilisateur'),
        ),
        migrations.CreateModel(
            name='Age_scolarise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_enfant_scolarise', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='NOMBRE ENFANT SCOLARISE')),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='age_enfant_scolarise', to='myapi.age', verbose_name='AGE')),
                ('enquete_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='age_enfant_scolarise', to='myapi.enquete_social')),
            ],
            options={
                'verbose_name_plural': '36. AGE ENFANTS SCOLARISES',
            },
        ),
        migrations.CreateModel(
            name='Age_enfant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_enfant', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='NOMBRE ENFANT')),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='age_enfant', to='myapi.age', verbose_name='AGE')),
                ('enquete_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='age_enfant_enquetes', to='myapi.enquete_social')),
            ],
            options={
                'verbose_name_plural': '35. AGE ENFANTS',
            },
        ),
    ]
