# Generated by Django 4.1.7 on 2023-11-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_projet_respo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='nomProjet',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
