# Generated by Django 4.2.6 on 2024-11-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_recolteproducteur_gap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recolteproducteur',
            name='gap',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=1000, null=True),
        ),
    ]
