# Generated by Django 4.2.6 on 2023-11-20 09:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_rdue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rdue',
            name='date',
        ),
        migrations.AddField(
            model_name='rdue',
            name='add_le',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rdue',
            name='update_le',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
