# Generated by Django 5.0.2 on 2024-11-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_alter_recolteproducteur_check_gap'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='sexe',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
