# Generated by Django 4.2.6 on 2025-05-12 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_monitoring_latitude_du_lieu_de_monitoring_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risquerdue',
            name='cooperative',
        ),
    ]
