# Generated by Django 5.2 on 2025-12-18 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_remove_risquerdue_cooperative'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='utilisateur',
        #     name='sexe',
        # ),
    ]
