# Generated by Django 5.0.2 on 2024-05-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0012_parcelle_image_du_titre_de_propriete'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelle',
            name='titre_de_propriete',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
