# Generated by Django 5.0.2 on 2024-05-08 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0013_parcelle_titre_de_propriete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcelle',
            name='annee_certificat',
        ),
        migrations.RemoveField(
            model_name='parcelle',
            name='certificat',
        ),
        migrations.RemoveField(
            model_name='parcelle',
            name='code_certif',
        ),
    ]
