# Generated by Django 5.0.2 on 2024-06-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0014_remove_parcelle_annee_certificat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelle',
            name='is_mapped',
            field=models.BooleanField(default=False),
        ),
    ]
