# Generated by Django 4.2.6 on 2024-03-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0015_projet_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquete',
            name='is_eau_potable',
            field=models.BooleanField(default=False, verbose_name='ACCES EAU POTABLE'),
        ),
    ]
