# Generated by Django 5.0.2 on 2024-06-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0015_parcelle_is_mapped'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelle',
            name='fichier_de_mappage',
            field=models.ImageField(null=True, upload_to='fichier_mapping/'),
        ),
    ]
