# Generated by Django 4.2.6 on 2024-03-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0016_alter_enquete_is_eau_potable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rdue',
            name='exp_illegale',
        ),
        migrations.RemoveField(
            model_name='rdue',
            name='liste_zone',
        ),
        migrations.AlterField(
            model_name='rdue',
            name='entite',
            field=models.CharField(choices=[('AGRIAL', 'AGRIAL'), ('COOPAA-HS', 'COOPAA-HS')], max_length=255, verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='rdue',
            name='evaluateur',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Enquêteur'),
        ),
        migrations.AlterField(
            model_name='rdue',
            name='produits',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Produits Commercialisés'),
        ),
        migrations.AlterField(
            model_name='rdue',
            name='zone_arisque',
            field=models.CharField(choices=[('OUI', 'OUI'), ('NON', 'NON')], default='ACTIVITE_CONTROVERSE', max_length=10, verbose_name='Activités portant à contreverse'),
        ),
    ]
