# Generated by Django 4.2.6 on 2024-03-29 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0018_alter_rdue_zone_arisque'),
    ]

    operations = [
        migrations.CreateModel(
            name='Angrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': '33. ANGRAIS',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Produit_Phyto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': '32. PRODUITS PHYTO',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Theme_Enquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': '31. THEMATIQUES ENQUETES SOCIALES',
                'ordering': ['libelle'],
            },
        ),
        migrations.RemoveField(
            model_name='rdue',
            name='action_comm',
        ),
        migrations.RemoveField(
            model_name='rdue',
            name='action_non_conformite',
        ),
        migrations.RemoveField(
            model_name='rdue',
            name='communication',
        ),
        migrations.AlterField(
            model_name='rdue',
            name='chaine_appro',
            field=models.CharField(blank=True, choices=[('MEMBRES', 'MEMBRES'), ('AUTRE', 'AUTRE')], default='MEMBRES', max_length=255, null=True, verbose_name='APPROVISIONNEMENT'),
        ),
        migrations.AlterField(
            model_name='rdue',
            name='entite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.cooperative', verbose_name='ORGANISATION'),
        ),
        migrations.AlterField(
            model_name='rdue',
            name='evaluateur',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ENQUETEUR'),
        ),
        migrations.AlterField(
            model_name='rdue',
            name='mesure_preventives',
            field=models.TextField(blank=True, null=True, verbose_name='Mesures Correctives'),
        ),
        migrations.AlterField(
            model_name='rdue',
            name='pays_origine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapi.countrie', verbose_name="PAYS D'ORIGINE"),
        ),
        migrations.AlterField(
            model_name='rdue',
            name='produits',
            field=models.CharField(choices=[('CACAO', 'CACAO'), ('CAFE', 'CAFE'), ('PALMIER', 'PALMIER A HUILE'), ('AUTRE', 'AUTRE')], default='CACAO', max_length=255, verbose_name='PRODUITS COMMERCIALISER'),
        ),
        migrations.AlterField(
            model_name='rdue',
            name='zone_arisque',
            field=models.CharField(choices=[('EXPLOITATION ILLEGALE DU BOIS', 'EXPLOITATION ILLEGALE DU BOIS'), ('ORPAILLAGE', 'ORPAILLAGE'), ('DEFORESTATION', 'DEFORESTATION'), ('TRAVAIL DES ENFANTS', 'TRAVAIL DES ENFANTS'), ('AUCUN', 'AUCUN')], default='AUCUN', max_length=255, verbose_name='Activités portant à contreverse'),
        ),
        migrations.DeleteModel(
            name='Enquete',
        ),
    ]
