# Generated by Django 4.2.6 on 2024-04-12 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0026_alter_acte_propriete_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme_enquete',
            options={'ordering': ['libelle'], 'verbose_name_plural': '31. THEMATIQUES ENQUETES'},
        ),
    ]
