# Generated by Django 5.0.2 on 2024-07-15 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0016_parcelle_fichier_de_mappage'),
        ('myapi', '0037_remove_recolteproducteur_lieu_production_and_more'),
    ]

    operations = [
    ]
