# Generated by Django 5.0.2 on 2024-02-27 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapi', '0011_cooperative_numconnaissement_cooperative_numregistre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technicien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooperative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.cooperative')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.utilisateur')),
            ],
        ),
    ]
