# Generated by Django 5.0.2 on 2024-05-08 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles_api', '0001_initial'),
        ('myapi', '0014_remove_parcelle_annee_certificat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, null=True)),
                ('annee', models.IntegerField(null=True)),
                ('certification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapi.certification')),
                ('parcelle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapi.parcelle')),
            ],
        ),
    ]
