# Generated by Django 5.0.2 on 2025-02-14 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapi', '0006_utilisateur_sexe'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeEnquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, unique=True)),
                ('libelle', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(max_length=255, unique=True)),
                ('est_ouverte', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.campagne')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.utilisateur')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.projet')),
            ],
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponses', models.JSONField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquete.enquete')),
                ('repondant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('est_obligatoire', models.BooleanField(default=True)),
                ('choix', models.JSONField(blank=True, null=True)),
                ('enquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquete.enquete')),
                ('type_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquete.typequestion')),
            ],
        ),
    ]
