# Generated by Django 5.0.2 on 2025-02-14 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquete', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeenquete',
            name='code',
        ),
    ]
