# Generated by Django 5.0.2 on 2025-02-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquete', '0002_remove_typeenquete_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeenquete',
            name='code',
            field=models.CharField(default='', max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
