# Generated by Django 5.0.2 on 2025-02-14 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquete', '0003_typeenquete_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquete',
            name='type_enquete',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='enquete.typeenquete'),
            preserve_default=False,
        ),
    ]
