# Generated by Django 5.0.2 on 2025-02-18 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquete', '0004_enquete_type_enquete'),
        ('myapi', '0006_utilisateur_sexe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enqueteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquete', models.ManyToManyField(to='enquete.enquete')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.utilisateur')),
            ],
        ),
    ]
