# Generated by Django 5.0.2 on 2025-02-18 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquete', '0005_enqueteur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enqueteur',
            old_name='enquete',
            new_name='enquetes',
        ),
    ]
