# Generated by Django 4.2.6 on 2025-05-19 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquete', '0006_rename_enquete_enqueteur_enquetes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.CharField(max_length=255)),
                ('question_cible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='enquete.question')),
                ('question_principale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquete.question')),
            ],
        ),
    ]
