# Generated by Django 4.2.6 on 2025-07-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquete', '0007_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeenquete',
            name='code',
        ),
        migrations.AddField(
            model_name='enquete',
            name='libelle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
