# Generated by Django 4.2.6 on 2024-11-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_alter_recolteproducteur_gap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recolteproducteur',
            name='check_gap',
            field=models.BooleanField(default=True),
        ),
    ]
