# Generated by Django 4.2.6 on 2025-08-29 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapi', '0008_remove_risquerdue_cooperative'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abattage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=255, null=True)),
                ('date', models.DateField(null=True)),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.parcelle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CategorieEthnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CategorieProduit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Conjoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=255, null=True)),
                ('nom_prenoms', models.CharField(max_length=255, null=True)),
                ('categorie', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Enfant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=255, null=True)),
                ('nom_prenoms', models.CharField(max_length=255, null=True)),
                ('date_naissance', models.DateField(null=True)),
                ('sexe', models.CharField(max_length=1, null=True)),
                ('statut_scolaire', models.CharField(max_length=255, null=True)),
                ('conjoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ars1000.conjoint')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnfantHasTacheChampetre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enfant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ars1000.enfant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Favorabilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndicateurRisqueTacheChampetre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(max_length=255, null=True)),
                ('est_homologue', models.BooleanField(null=True)),
                ('categorie_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ars1000.categorieproduit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatutMatrimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatutMenage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeActionMesureAttenuationPhyto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeActionMesureAttenuationTacheChampetre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeMesureAttenuationAgroforesterie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeProduit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeScolarite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeTachesChampetre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TacheChampetre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(max_length=255, null=True)),
                ('type_taches_champetre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ars1000.typetacheschampetre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Scolarite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(max_length=255, null=True)),
                ('type_scolarite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ars1000.typescolarite')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RapportAuditInterne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom_prenoms_auditeur', models.CharField(max_length=255, null=True)),
                ('rapport_audit', models.FileField(null=True, upload_to='documents/coops')),
                ('liste_des_audites', models.FileField(null=True, upload_to='documents/coops')),
                ('plan_action_correctif', models.FileField(null=True, upload_to='documents/coops')),
                ('fiche_non_conformite', models.FileField(null=True, upload_to='documents/coops')),
                ('date_enregistrement', models.DateField(null=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.cooperative')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProduitHasProducteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_de_livraison', models.DateField(null=True)),
                ('cooperative', models.CharField(max_length=255, null=True)),
                ('producteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.producteur')),
                ('produits', models.ManyToManyField(to='ars1000.produit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='produit',
            name='type_produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ars1000.typeproduit'),
        ),
        migrations.CreateModel(
            name='PlanningAnnuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.FileField(null=True, upload_to='documents/coops')),
                ('campagne', models.CharField(max_length=255, null=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.cooperative')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParcelleHasProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_application', models.DateField(null=True)),
                ('dose_par_ha', models.FloatField(null=True)),
                ('applicateur', models.CharField(max_length=255, null=True)),
                ('utilisation_epi', models.BooleanField(null=True)),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.parcelle')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ars1000.produit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organigramme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom_prenoms', models.CharField(max_length=255, null=True)),
                ('competence', models.CharField(max_length=255, null=True)),
                ('poste', models.CharField(max_length=255, null=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.cooperative')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MesureAttenuationTacheChampetre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(null=True)),
                ('cible', models.CharField(max_length=255, null=True)),
                ('localite', models.CharField(max_length=255, null=True)),
                ('motifs', models.ManyToManyField(to='ars1000.enfanthastachechampetre')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.section')),
                ('type_action_mesure_attenuation_tache_champetre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ars1000.typeactionmesureattenuationtachechampetre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MesureAttenuationPhyto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(null=True)),
                ('cible', models.CharField(max_length=255, null=True)),
                ('motifs', models.ManyToManyField(to='ars1000.parcellehasproduit')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.section')),
                ('type_mesure_attenuation_phyto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ars1000.typeactionmesureattenuationphyto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MesureAttenuationAgroforesterie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cible', models.CharField(max_length=255, null=True)),
                ('date', models.DateField(null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.section')),
                ('type_mesure_attenuation_agroforesterie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ars1000.typemesureattenuationagroforesterie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InformationCooperative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_cooperative', models.CharField(max_length=255, null=True)),
                ('statut', models.FileField(null=True, upload_to='documents/coops')),
                ('pv_assemblee', models.FileField(null=True, upload_to='documents/coops')),
                ('liste_membres', models.FileField(null=True, upload_to='documents/coops')),
                ('numero_compte_contribuable', models.CharField(max_length=255, null=True)),
                ('numero_cnps', models.CharField(max_length=255, null=True)),
                ('numero_aggrement', models.CharField(max_length=255, null=True)),
                ('immatriculation_ccc', models.CharField(max_length=255, null=True)),
                ('existence_discrimination', models.BooleanField(null=True)),
                ('conformite_ohada', models.BooleanField(null=True)),
                ('cooperative', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapi.cooperative')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InfoProducteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_ccc', models.CharField(max_length=255, null=True)),
                ('categorie_ethnique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ars1000.categorieethnique')),
                ('producteur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapi.producteur')),
                ('statut_matrimonial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ars1000.statutmatrimonial')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InfoParcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('precedent_cultural', models.CharField(max_length=255, null=True)),
                ('origine_materiel', models.CharField(max_length=255, null=True)),
                ('parcelle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapi.parcelle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnfantScolarite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.campagne')),
                ('enfant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ars1000.enfant')),
                ('scolarite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ars1000.scolarite')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnfantHasTacheChampetreHasIndicateurRisqueTacheChampetre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enfant_has_tache_champetre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ars1000.enfanthastachechampetre')),
                ('indicateur_risque_tache_champetre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ars1000.indicateurrisquetachechampetre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='enfanthastachechampetre',
            name='parcelle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ars1000.infoparcelle'),
        ),
        migrations.AddField(
            model_name='enfanthastachechampetre',
            name='tache_champetre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ars1000.tachechampetre'),
        ),
        migrations.AddField(
            model_name='enfant',
            name='producteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ars1000.infoproducteur'),
        ),
        migrations.CreateModel(
            name='DocumentationFonciere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organe_delivrance', models.CharField(max_length=255, null=True)),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.parcelle')),
                ('statut_producteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ars1000.statutmenage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetailMesureAttenuationAgroforesteriePlanting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mesure_attenuation_agroforesterie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ars1000.mesureattenuationagroforesterie')),
                ('planting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.planting')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetailMesureAttenuationAgroforesterieAbattage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('abattage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ars1000.abattage')),
                ('mesure_attenuation_agroforesterie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ars1000.mesureattenuationagroforesterie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetailAbattage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nbre_plant', models.IntegerField(null=True)),
                ('abattage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ars1000.abattage')),
                ('espece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.espece')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='conjoint',
            name='producteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ars1000.infoproducteur'),
        ),
        migrations.CreateModel(
            name='AvantageCultureEspece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.culture')),
                ('espece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.espece')),
                ('favorabilite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ars1000.favorabilite')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActionMenee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(max_length=255, null=True)),
                ('ressources_dispo', models.CharField(max_length=255, null=True)),
                ('analyse_swot', models.CharField(max_length=255, null=True)),
                ('besoin_financier', models.IntegerField(null=True)),
                ('date', models.DateField(null=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.cooperative')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.section')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
