# Generated by Django 5.2 on 2025-12-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ars1000', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conjoint',
            name='date_naissance',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='conjoint',
            name='sexe',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
