# Generated by Django 4.1.7 on 2023-10-28 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=200, null=True)),
                ('dateDebut', models.DateField(blank=True, null=True)),
                ('DateFin', models.DateField(blank=True, null=True)),
                ('etat', models.BooleanField(default=True)),
                ('duree_campagne', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '05. Campagnes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CategorieEspece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': '06. Categories especes',
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '27. CERTIFICATION PARCELLE',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Cooperative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respCoop', models.CharField(blank=True, max_length=255, null=True)),
                ('nomCoop', models.CharField(blank=True, max_length=500, null=True)),
                ('contacts', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.ImageField(null=True, upload_to='logo_coop/')),
                ('etat', models.BooleanField(default=True)),
                ('siege', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '12. Cooperatives',
            },
        ),
        migrations.CreateModel(
            name='Countrie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': '01. Pays',
            },
        ),
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=250, null=True)),
                ('prix_unitaire_culture', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cooperative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.cooperative')),
            ],
            options={
                'verbose_name_plural': '16. Cultures',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Espece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accronyme', models.CharField(max_length=250, verbose_name='NOM SCIENTIFIQUE')),
                ('libelle', models.CharField(max_length=250, unique=True, verbose_name='NOM USUEL')),
                ('densite', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='DENSITE SPECIFIQUE')),
                ('hmax', models.FloatField(default=0)),
                ('dmax', models.FloatField(default=0)),
                ('co2_annuel', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='CO2/AN')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.categorieespece')),
            ],
            options={
                'verbose_name_plural': '07. Especes',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='GroupeProducteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '14. Groupe de producteurs',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='ModeAcquisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': "17. Mode d'acquisition",
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Monitoring',
            fields=[
                ('code', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('taux_reussite', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campagne', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.campagne')),
            ],
            options={
                'verbose_name_plural': '21. Monitoring',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ObservationMortalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': '23. Cause de mortalite',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('code', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('latitude', models.CharField(blank=True, max_length=200, null=True)),
                ('longitude', models.CharField(blank=True, max_length=200, null=True)),
                ('superficie', models.FloatField(default=0)),
                ('code_certif', models.CharField(blank=True, max_length=150, null=True)),
                ('annee_certificat', models.CharField(blank=True, max_length=150, null=True)),
                ('annee_acquis', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acquisition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.modeacquisition')),
                ('campagne', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.campagne')),
                ('certificat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.certification')),
                ('culture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.culture')),
            ],
            options={
                'verbose_name_plural': '18. Parcelles',
            },
        ),
        migrations.CreateModel(
            name='Producteur',
            fields=[
                ('code', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('nomComplet', models.CharField(blank=True, max_length=250, null=True)),
                ('contacts', models.CharField(blank=True, max_length=50, null=True)),
                ('photo', models.ImageField(null=True, upload_to='photo_prod/')),
                ('nbParc', models.IntegerField(default=0)),
                ('etat', models.BooleanField(default=True)),
                ('lieu_habitation', models.CharField(blank=True, max_length=150, null=True)),
                ('representant', models.CharField(blank=True, max_length=250, null=True)),
                ('nbreMembre', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campagne', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.campagne')),
                ('groupe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.groupeproducteur')),
            ],
            options={
                'verbose_name_plural': '15. Producteurs',
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomProjet', models.CharField(max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('dateDebut', models.DateField(blank=True, null=True)),
                ('dateFin', models.DateField(blank=True, null=True)),
                ('objectif', models.CharField(blank=True, max_length=100, null=True)),
                ('etat', models.BooleanField(default=True)),
                ('plant_aproduit', models.FloatField(default=0)),
                ('carbon_astock', models.FloatField(default=0)),
                ('emp_engageof_proj', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('countrie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.countrie')),
            ],
            options={
                'verbose_name_plural': '03. Projets',
            },
        ),
        migrations.CreateModel(
            name='SimulateCarbon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anneePeuplement', models.IntegerField(default=1)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('totalCarbone', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '08. Simulation carbone',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('nom', models.CharField(max_length=100, null=True)),
                ('prenom', models.CharField(max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('tel', models.CharField(max_length=100, null=True)),
                ('sexe', models.CharField(max_length=50, null=True)),
                ('date_adh_agromap', models.DateField(blank=True, null=True)),
                ('fonction', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=300)),
                ('is_online', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superadmin', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_client', models.BooleanField(default=False)),
                ('is_responsable', models.BooleanField(default=False)),
                ('is_supervisor', models.BooleanField(default=False)),
                ('is_gestionnaire', models.BooleanField(default=False)),
                ('is_adg', models.BooleanField(default=False)),
                ('is_technicien', models.BooleanField(default=False)),
                ('is_pepinieriste', models.BooleanField(default=False)),
                ('permission_ptr', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='utilisateur', to='auth.permission')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for the user utilisateur.', null=True, related_name='utilisateurs', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': '02. Utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='UserProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etatuser', models.BooleanField(default=True)),
                ('projet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.projet')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.utilisateur')),
            ],
            options={
                'verbose_name_plural': '04. Users on projects',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cooperative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.cooperative')),
            ],
            options={
                'verbose_name_plural': '13. Sections',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='SaisonRecolte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=250, null=True)),
                ('cooperative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.cooperative')),
            ],
            options={
                'verbose_name_plural': '25. Saisons de recolte',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=250, null=True)),
                ('chef_lieu_reg', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('countrie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.countrie')),
            ],
            options={
                'verbose_name_plural': '11. Regions',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='RecolteProducteur',
            fields=[
                ('code', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('lieu_production', models.CharField(blank=True, max_length=200, null=True)),
                ('nbre_sacs', models.IntegerField(default=0)),
                ('poids_total', models.FloatField(default=0)),
                ('prix_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campagne', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.campagne')),
                ('culture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.culture')),
                ('producteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.producteur')),
                ('saison', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.saisonrecolte')),
            ],
            options={
                'verbose_name_plural': '26. Recoltes producteurs',
            },
        ),
        migrations.AddField(
            model_name='producteur',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.section'),
        ),
        migrations.CreateModel(
            name='Planting',
            fields=[
                ('code', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('plant_existant', models.IntegerField(default=0)),
                ('plant_recus', models.IntegerField(default=0)),
                ('note_plant_existant', models.TextField(null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campagne', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.campagne')),
                ('parcelle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.parcelle')),
            ],
            options={
                'verbose_name_plural': '19. Plantings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='parcelle',
            name='producteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.producteur'),
        ),
        migrations.CreateModel(
            name='ObservationMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitoring', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.monitoring')),
                ('observation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.observationmortalite')),
            ],
            options={
                'verbose_name_plural': '24. Observations monitoring',
            },
        ),
        migrations.CreateModel(
            name='MonitoringDetail',
            fields=[
                ('code', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('plant_denombre', models.IntegerField(default=0)),
                ('taux_reussite', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('espece', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.espece')),
                ('monitoring', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.monitoring')),
            ],
            options={
                'verbose_name_plural': '22. Monitoring par espèces',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='monitoring',
            name='planting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.planting'),
        ),
        migrations.CreateModel(
            name='EspeceSimulate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('carboneStocke', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('espece', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.espece')),
                ('simulate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.simulatecarbon')),
            ],
            options={
                'verbose_name_plural': '09. Especes de simulation',
            },
        ),
        migrations.CreateModel(
            name='DetailPlanting',
            fields=[
                ('code', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('plants', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('espece', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.espece')),
                ('planting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.planting')),
            ],
            options={
                'verbose_name_plural': '20. Especes Plantées',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='cooperative',
            name='projet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.projet'),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.region'),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='respo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.utilisateur'),
        ),
        migrations.CreateModel(
            name='CampagneProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campagne', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.campagne')),
                ('projet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.projet')),
            ],
            options={
                'verbose_name_plural': '10. Campagnes par projets',
            },
        ),
        migrations.AddField(
            model_name='campagne',
            name='respo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.utilisateur'),
        ),
    ]
