# Generated by Django 4.2.6 on 2023-12-04 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_alter_rdue_options_alter_risquerdue_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rdue',
            options={'verbose_name_plural': '29. QUESTIONNAIRES RDUE'},
        ),
    ]
