# Generated by Django 4.2.6 on 2024-01-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0010_risquerdue_cooperative'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperative',
            name='numConnaissement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='numRegistre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
