# Generated by Django 4.2.6 on 2024-03-16 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0011_cooperative_numconnaissement_cooperative_numregistre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': '30. TRANCHES AGES',
            },
        ),
        migrations.CreateModel(
            name='Enquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_epouse', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name="NBRE D'EPOUSE ")),
                ('enfant_mineur', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='ENFANTS MINEURS')),
                ('enfant_majeur', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='ENFANTS MAJEURS')),
                ('nb_enfant', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name="NBRE TOTAL D'ENFANTS")),
                ('enfant_scolarise', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='ENFANTS SCOLARISES')),
                ('nb_personne', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='PERSONNES A CHARGE')),
                ('is_manoeuvre', models.CharField(blank=True, choices=[('OUI', 'OUI'), ('NON', 'NON')], max_length=10, null=True, verbose_name='UTILISEZ-VOUS DES MANOEUVRES ?')),
                ('is_manoeuvre_femme', models.CharField(blank=True, choices=[('OUI', 'OUI'), ('NON', 'NON')], max_length=10, null=True, verbose_name="Recours aux femmes comme main d'œuvre dans l'activité")),
                ('nb_manoeuvre_femme', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='NB FEMME MANOEUVRE')),
                ('type_manoeuvre', models.CharField(blank=True, choices=[('FAMILLE', 'FAMILLE'), ('EXTERIEURE', 'EXTERIEURE')], max_length=10, null=True)),
                ('nb_manoeuvre', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='NBRE DE MANOEUVRES')),
                ('is_ouvrier_mineur', models.CharField(blank=True, choices=[('OUI', 'OUI'), ('NON', 'NON')], max_length=10, null=True, verbose_name='UTILISEZ-VOUS DES MANOEUVRES MINEURS')),
                ('nb_ouvrier_mineur', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='NBRE DE MANOEUVRES MINEURS')),
                ('salaire_ouvrier', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='SALAIRE MOYEN/OUVRIER')),
                ('utilisation_produit_phyto', models.CharField(choices=[('OUI', 'OUI'), ('NON', 'NON')], max_length=10)),
                ('is_eau_potable', models.CharField(blank=True, choices=[('OUI', 'OUI'), ('NON', 'NON')], max_length=10, null=True, verbose_name='ACCES EAU POTABLE')),
                ('is_electricite', models.CharField(blank=True, choices=[('OUI', 'OUI'), ('NON', 'NON')], max_length=10, null=True, verbose_name='ACCES ELECTRICITE')),
                ('is_soins', models.CharField(blank=True, choices=[('OUI', 'OUI'), ('NON', 'NON')], max_length=10, null=True, verbose_name='ACCES AUX SOINS')),
                ('nb_dispensaire', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='NOMBRE DE CENTRE DE SANTE DANS LA LOCALITE')),
                ('dtce_dispensaire', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='DISTANCE MOYENNE AU CENTRE DE SANTE LE PLUS PROCHE')),
                ('nb_ecole_primaire', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name="NOMBRE D'ECOLES PRIMARE DANS LA LOCALITE")),
                ('dtce_ecole_primaire', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="DISTANCE MOYENNE A L'ECOLE PRIMAIRE LA PLUS PROCHE")),
                ('is_college', models.CharField(blank=True, choices=[('OUI', 'OUI'), ('NON', 'NON')], max_length=10, null=True, verbose_name="LA LOCALITE DISPOSE-T-ELLE D'UN COLLEGE/LYCEE ?")),
                ('nb_college', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='NOMBRE DE COLLEGES/LYCEE DANS LA LOCALITE')),
                ('dtce_college', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='DISTANCE MOYENNE COLLEGE/LYCEE LE PLUS PROCHE')),
                ('is_banque', models.CharField(blank=True, choices=[('OUI', 'OUI'), ('NON', 'NON')], max_length=10, null=True, verbose_name="LA LOCALITE DISPOSE-T-ELLE D'ETABLISSEMENT FINACIER ?")),
                ('nb_banque', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name="NOMBRE D'ETABLISSEMENT FINACIER DANS LA LOCALITE")),
                ('dtce_banque', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='DISTANCE MOYENNE ETABLISSEMENT FINACIER LE PLUS PROCHE')),
                ('producteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquetes_producteur', to='myapi.producteur')),
            ],
        ),
    ]
