# Generated by Django 4.2.6 on 2024-03-16 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0012_age_enquete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquete',
            options={'verbose_name_plural': '31. ENQUETES SOCIALE'},
        ),
    ]
