# Generated by Django 4.2.6 on 2024-03-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0013_alter_enquete_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelle',
            name='superficie',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
