# Generated by Django 4.2.6 on 2024-03-17 16:34

from django.db import migrations, models
import myapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0014_alter_parcelle_superficie'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='logo',
            field=models.ImageField(blank=True, upload_to=myapi.models.upload_logo_site, verbose_name='Logo'),
        ),
    ]
