# Generated by Django 4.2.6 on 2024-03-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0017_remove_rdue_exp_illegale_remove_rdue_liste_zone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdue',
            name='zone_arisque',
            field=models.CharField(choices=[('ORPAILLAGE', 'ORPAILLAGE'), ('EXPLOITATION ILLEGALE DU BOIS', 'EXPLOITATION ILLEGALE DU BOIS')], default='', max_length=255, verbose_name='Activités portant à contreverse'),
        ),
    ]
