# Generated by Django 4.2.6 on 2024-03-29 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0020_alter_angrais_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Angrais',
            new_name='Engrais',
        ),
    ]
