# Generated by Django 4.2.6 on 2024-04-12 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0025_alter_detail_engrais_engrais'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acte_propriete',
            options={'ordering': ['libelle'], 'verbose_name_plural': '41. ACTE DE PROPIETE'},
        ),
    ]
