# Generated by Django 4.2.6 on 2024-04-12 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0027_alter_theme_enquete_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acte_propriete',
            options={'ordering': ['libelle'], 'verbose_name_plural': '41. ACTE DE PROPRIETE'},
        ),
    ]
