# Generated by Django 4.2.6 on 2024-05-27 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0028_alter_acte_propriete_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperative',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.projet'),
        ),
    ]
