# Generated by Django 4.2.6 on 2024-06-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0030_parcelle_is_map'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcelle',
            old_name='is_map',
            new_name='is_mapped',
        ),
        migrations.AddField(
            model_name='parcelle',
            name='fichier_de_mappage',
            field=models.FileField(blank=True, null=True, upload_to='fichier_mapping/'),
        ),
    ]
