# Generated by Django 4.2.6 on 2024-07-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0032_sectionpoint_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='latitude',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='point',
            name='longitude',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
