# Generated by Django 4.2.6 on 2024-07-04 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0036_point_point_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recolteproducteur',
            name='lieu_production',
        ),
        migrations.RemoveField(
            model_name='recolteproducteur',
            name='producteur',
        ),
        migrations.AddField(
            model_name='recolteproducteur',
            name='estimation_production',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='recolteproducteur',
            name='parcelle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.parcelle'),
        ),
        migrations.AlterField(
            model_name='recolteproducteur',
            name='poids_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=1000, null=True),
        ),
    ]
