from django.shortcuts import render

from .views_classes.utilisateur_view import UtilisateurViewSet
from .views_classes.cooperative_view import CooperativeViewSet
from .views_classes.section_view import SectionViewSet
from .views_classes.campagne_view import CampagneViewSet
from .views_classes.producteur_view import ProducteurViewSet
from .views_classes.parcelle_view import ParcelleViewSet
from .views_classes.planting_view import PlantingViewSet
from .views_classes.detailplanting_view import DetailPlantingViewSet
from .views_classes.certification_view import CertificationViewSet, CertificatViewSet
from .views_classes.culture_view import CultureViewSet
from .views_classes.modeacquisition_view import ModeAcquisitionViewSet
from .views_classes.espece_view import EspeceViewSet
from .views_classes.actepropriete_view import ActeProprieteViewSet
from .views_classes.monitoring_view import MonitoringViewSet
from .views_classes.detailmonitoring_view import DetailMonitoringViewSet
from .views_classes.observationmortalite_view import ObservationMortaliteViewSet
from .views_classes.observationmonitoring_view import ObservationMonitoringViewSet
