# Generated by Django 5.0.2 on 2024-12-02 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles_api', '0002_compensationpse'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieActiviteRetribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ActiviteRetribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='mobiles_api.categorieactiviteretribution')),
            ],
        ),
    ]
