# Generated by Django 5.0.2 on 2024-12-02 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles_api', '0003_categorieactiviteretribution_activiteretribution'),
        ('myapi', '0006_utilisateur_sexe'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPSE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pourcentage_retribution', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=1000, null=True)),
                ('montant_pse', models.IntegerField()),
                ('activites', models.ManyToManyField(to='mobiles_api.activiteretribution')),
                ('campagne', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infos_pse', to='myapi.campagne')),
                ('compensation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infos_pse', to='mobiles_api.compensationpse')),
                ('projet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infos_pse', to='myapi.projet')),
            ],
        ),
    ]
