# Generated by Django 5.0.2 on 2025-03-26 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles_api', '0004_infopse'),
        ('myapi', '0006_utilisateur_sexe'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArbreExistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbre_de_regeneration_naturelle', models.IntegerField()),
                ('nbre_de_regeneration_assistee', models.IntegerField()),
                ('nbre_plantee', models.IntegerField()),
                ('picture', models.ImageField(upload_to='images_especes_existantes_sur_parcelle/')),
                ('espece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.espece')),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.parcelle')),
            ],
        ),
    ]
