# Generated by Django 5.0.2 on 2025-03-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles_api', '0005_arbreexistant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbreexistant',
            name='picture',
            field=models.ImageField(upload_to='images_especes/'),
        ),
    ]
