# Generated by Django 5.0.2 on 2025-03-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles_api', '0006_alter_arbreexistant_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbreexistant',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images_especes/'),
        ),
    ]
