# Generated by Django 5.0.2 on 2025-03-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles_api', '0007_alter_arbreexistant_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbreexistant',
            name='nbre_de_regeneration_assistee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='arbreexistant',
            name='nbre_de_regeneration_naturelle',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='arbreexistant',
            name='nbre_plantee',
            field=models.IntegerField(default=0),
        ),
    ]
