# Generated by Django 4.2.6 on 2024-10-16 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technicien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooperative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.cooperative')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Certificat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, null=True)),
                ('annee', models.IntegerField(null=True)),
                ('certification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapi.certification')),
                ('parcelle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapi.parcelle')),
            ],
        ),
    ]
